#ifndef __SENSOR_DB_OPERATION_H_
#define __SENSOR_DB_OPERATION_H_

enum E_SensorDBOperation
{
	SENSOR_DB_VERIFY_ACCOUNT,
	SENSOR_DB_SLOPE_LIST,
	SENSOR_DB_SENSOR_LIST,
	SENSOR_DB_SENSOR_HISTORY,

	SENSOR_DB_OPT_MAX,
};

#endif
